# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'swipeMonthYear' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for swipeMonthYear

  target 'swipeMonthYearTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swipeMonthYearUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
